# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b9914d8d2d3ff4c34dd78ff67abac9bb44f29903cda824f253d80d6bc21cd12f566e8d0e52def84de685f0bf4edc255748e737c4764a4063b8fb94eba84d1e3

test:
  secret_key_base: 6225b79a992d008f3abeaab35664976c93ac01d82625e8484327b51efb48f0a1a92df60a372757f5729a31ebc1adab1c92dd29129b19c9ee2dbea79c1112764a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
